name: CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      -
        run: docker build .
